-- SELECT SELLER.FIRST_NAME AS 'seller_first_name',
-- SELLER.LAST_NAME  AS 'seller_last_name', 
-- BUYER.FIRST_NAME AS 'buyer_first_name', 
-- BUYER.LAST_NAME  AS 'buyer_last_name',
-- O.*,
-- P.*,
-- PAY.*
-- FROM ORDERS O JOIN USERS BUYER ON O.CUSTOMER_ID = BUYER.USER_ID AND BUYER.ROLE_TYPE = 'BUYER'
-- 		      JOIN ORDERDETAILS OD ON O.ORDER_ID = OD.ORDER_ID
-- 			  JOIN PRODUCTS P ON P.PRODUCT_ID = OD.PRODUCT_ID
--               JOIN PAYMENTS PAY ON O.PAYMENT_ID = PAY.PAYMENT_ID
-- 			  JOIN USERS SELLER ON (SELLER.USER_ID = P.SELLER_ID AND SELLER.ROLE_TYPE = 'SELLER');
--               
-- SELECT P.PRODUCT_NAME, P.PRICE_PER_UNIT
-- FROM PRODUCTS P;

-- SELECT *
-- FROM USERS;

-- SELECT *
-- FROM ORDERS;

-- SELECT *
-- FROM PRODUCTS;

-- SELECT *
-- FROM ORDERDETAILS;

-- SELECT *
-- FROM PAYMENTS;

